
version: "3.9"


networks:
    mynetwork:
        driver: bridge

services:

  #######################################
  #  Process Services
  #######################################


 



  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    ports:
      - 8024:8024
      - 8124:8124
    expose:
      - '8124'
      - '8024'       
    networks:
      - mynetwork


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine    
    ports:
      - '15672:15672'
      - '5672:5672'
    expose:
      - '15672'     
      - '5672'  
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
    networks:
      - mynetwork


  accountservice:
    container_name: accountservice
    restart: on-failure
    build:
        context: ./AccountService
        dockerfile: Dockerfile  
    ports:
      - "8081:8081"
    expose:
      - '8081'
    depends_on:
      - rabbitmq
      - axonserver 
    networks:
      - mynetwork

  claimservice:
    container_name: claimservice
    restart: on-failure
    build:
        context: ./ClaimService
        dockerfile: Dockerfile  
    ports:
      - "8083:8083"
    expose:
      - '8083'
    depends_on:
      - rabbitmq
      - axonserver 
    networks:
      - mynetwork

  payoutservice:
    container_name: payoutservice
    restart: on-failure
    build:
        context: ./PayoutService
        dockerfile: Dockerfile  
    ports:
      - "8084:8084"
    expose:
      - '8084'
    depends_on:
      - rabbitmq
      - axonserver 
    networks:
      - mynetwork


  processorservice:
    container_name: processorservice
    restart: on-failure
    build:
        context: ./ProcessorService
        dockerfile: Dockerfile  
    ports:
      - "8085:8085"
    expose:
      - '8085'
    depends_on:
      - rabbitmq
      - axonserver 
    networks:
      - mynetwork


  transferservice:
    container_name: transferservice
    restart: on-failure
    build:
        context: ./TransferService
        dockerfile: Dockerfile  
    ports:
      - "8082:8082"
    expose:
      - '8082'
    depends_on:
      - rabbitmq
      - axonserver 
    networks:
      - mynetwork
